language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
os:
  - linux
env:
  - CC=gcc CXX=g++
  - CC=clang CXX=clang++

matrix:
  include:
    - python: "2.7"
      env: TEST_COMMAND=lint

addons:
  apt:
    packages:
      - libboost-dev
      - libboost-program-options-dev
      - libogg-dev
      - ninja-build

before_install:
  - wget https://nixos.org/releases/patchelf/patchelf-0.8/patchelf-0.8.tar.gz
  - tar -xzf patchelf-0.8.tar.gz
  - pushd patchelf-0.8 && ./configure --prefix=$VIRTUAL_ENV && make && make install && popd
install:
  - pip install flake8
  - pip install .
script:
  - python setup.py ${TEST_COMMAND-test -q}
