language: python
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
os:
  - linux
env:
  - CC=gcc CXX=g++
  - CC=clang CXX=clang++

matrix:
  include:
    - language: generic
      python: 2.7
      os: osx
      env: CC=gcc CXX=g++
    - python: 2.7
      os: linux
      env: TEST_COMMAND=lint

addons:
  apt:
    packages:
      - libboost-dev
      - libboost-program-options-dev
      - libogg-dev
      - ninja-build

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      brew install python
      brew install coreutils
      brew install ninja
      brew install libogg
    fi
install:
  - pip install flake8
  - pip install .
script:
  - python setup.py ${TEST_COMMAND-test -q}
