language: python
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
os:
  - linux
env:
  global:
    - PYTHON=python
    - PIP=pip
    - TEST_COMMAND="test -q"
    - CPPFLAGS="-Wall -Werror"
  matrix:
    - CC=gcc CXX=g++
    - CC=clang CXX=clang++

matrix:
  include:
    - language: generic
      python: 2.7
      os: osx
      env: CC=clang CXX=clang++
    - language: generic
      python: 3.5
      os: osx
      env: CC=clang CXX=clang++ PYTHON=python3 PIP=pip3
    - python: 2.7
      os: linux
      env: TEST_COMMAND=lint

addons:
  apt:
    packages:
      - gfortran
      - gobjc
      - gobjc++
      - libboost-dev
      - libboost-program-options-dev
      - libogg-dev
      - ninja-build
cache:
  - apt

before_install:
  - set -e
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      brew install coreutils
      brew install libogg
      brew install ninja
      brew install ${PYTHON}
    fi
install:
  - |
    if [ "${TEST_COMMAND}" = "lint" ]; then
      ${PIP} install flake8
    fi
  - git clone https://github.com/jimporter/doppel.git
  - ${PIP} install ./doppel .
script:
  - ${PYTHON} setup.py ${TEST_COMMAND}
