language: python
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
os:
  - linux
env:
  global:
    - PYTHON=python
    - PIP=pip
    - CPPFLAGS="-Wall -Werror"
  matrix:
    - CC=gcc CXX=g++
    - CC=clang CXX=clang++

matrix:
  include:
    - language: generic
      python: 2.7
      os: osx
      env: >
        PYTHON=python2 PIP=pip2 CC=clang CXX=clang++ NO_SCALA_TEST=1
        NO_GCJ_TEST=1
    - language: generic
      python: 3.6
      os: osx
      env: >
        PYTHON=python3 PIP=pip3 CC=clang CXX=clang++ NO_SCALA_TEST=1
        NO_GCJ_TEST=1
    - python: 2.7
      os: linux
      env: JOB=lint
      script: ${PYTHON} setup.py lint

addons:
  apt:
    packages:
      - freeglut3-dev
      - gfortran
      - gobjc
      - gobjc++
      - gcj-jdk
      - libboost-dev
      - libboost-program-options-dev
      - libgl1-mesa-dev
      - libogg-dev
      - ninja-build
      - openjdk-7-jdk
      - scala
cache:
  - apt

before_install:
  - set -e
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      shell_session_update() { :; }
      brew update
      brew cask uninstall oclint
      brew install gcc libogg ninja
      if [ "${PYTHON}" = "python3" ]; then
        brew install ${PYTHON} || brew upgrade ${PYTHON}
      fi
      cp test/scripts/sitecustomize.py .
    else
      export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
      unset _JAVA_OPTIONS
    fi
install:
  - ${PIP} install codecov .[test]
script:
  - ${PYTHON} setup.py coverage -q
after_success:
  - codecov
