build: false
environment:
  BOOST_INCLUDEDIR: C:\Libraries\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost\lib32-msvc-12.0
  CPPFLAGS: /IC:\projects\bfg9000\libogg-1.3.2\include
  LIBRARY_PATH: C:\projects\bfg9000\libogg-1.3.2\lib

  matrix:
    - PYTHON: C:\Python27
      VS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
install:
  - call scripts\appveyor_install_libogg.bat
  - cinst ninja
  - cinst gnuwin32-coreutils.portable
  - call "%VS%" x86
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - easy_install lxml
  - pip install .
test_script:
  - set BACKENDS=ninja msbuild
  - python setup.py test