site_name: bfg9000
docs_dir: doc
repo_url: https://github.com/jimporter/bfg9000/
theme: yeti

extra_css:
- css/extra.css

markdown_extensions:
- admonition

pages:
- Home: index.md
- User Guide:
  - Building with bfg9000: building.md
- Developer Guide: developer.md
- License: license.md
