site_name: bfg9000
docs_dir: doc
repo_url: https://github.com/jimporter/bfg9000/
copyright: Copyright &copy; 2015-2017 Jim Porter

theme: yeti
extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: ยง

pages:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Building with bfg9000: user/building.md
      - Writing a Build File: user/writing.md
      - Reference: user/reference.md
      - Environment Variables: user/environment-vars.md
  - Developer Guide:
      - Internals: developer/internals.md
      - Contributing: developer/contributing.md
  - About:
      - Changes: about/changes.md
      - License: about/license.md
