site_name: bfg9000
docs_dir: doc
repo_url: https://github.com/jimporter/bfg9000/

theme: yeti
extra_css:
- css/extra.css

markdown_extensions:
- admonition
- attr_list

pages:
- Home: index.md
- User Guide:
  - Building with bfg9000: user/building.md
  - Reference: user/reference.md
  - Environment Variables: user/environment-vars.md
- Developer Guide: developer.md
- License: license.md
