site_name: bfg9000
docs_dir: doc
repo_url: https://github.com/jimporter/bfg9000/
edit_uri: ""
copyright: Copyright &copy; 2015-2018 Jim Porter

theme: yeti
extra_css:
  - css/extra.css
  - css/version-select.css
extra_javascript:
  - js/version-select.js

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: ยง

pages:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Features: user/features.md
      - Building with bfg9000: user/building.md
      - Writing a Build File: user/writing.md
      - Reference: user/reference.md
      - Command-Line Reference: user/command-line.md
      - Environment Variables: user/environment-vars.md
  - Developer Guide:
      - Build Backends: developer/backends.md
      - Build Tools: developer/tools.md
      - Builtins: developer/builtins.md
      - Contributing: developer/contributing.md
  - About:
      - Changes: about/changes.md
      - License: about/license.md
